name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Log event and environment
        run: |
          echo "The job was triggered by a ${{ github.event_name }} event."
          echo "Running on ${{ runner.os }} hosted by GitHub."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: gradle

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Get Android version
        id: test
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle.kts

      - name: Print version details
        shell: bash
        run: |
          echo "versionCode: ${{ steps.test.outputs.versionCode }}"
          echo "versionName: ${{ steps.test.outputs.versionName }}"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_RELEASE }}
        run: |
          gh release create "${{ steps.test.outputs.versionName }}-${{ steps.test.outputs.versionCode }}" \
            --title "Release version ${{ steps.test.outputs.versionName }}-${{ steps.test.outputs.versionCode }}" \
            --notes "Automated release from CI" \
            ./app/build/outputs/apk/debug/app-debug.apk
